.vscode/extensions.json

- 필요없는 패키지라 제거했습니다.
- 이 PR과 관련된 이슈 번호를 적어주세요. (예: `#123`)
- 베타버전 안 사용하니 필요없을 것 같았어요.
- .vscode 폴더 내부 recommended package 에서 ts-next 삭제
- vscode 내에 설치하셨다면 지워주셔도 됩니다.

chore: 🔧 remove ts-next package

---

LICENSE

- 레파지토리를 공개하고 gpl v3라이센스를 추가합니다.

chore: add gpl v3

---

.gitignore
.vscode/cspell.json
packages/ui/.gitignore
packages/ui/.storybook/main.ts
packages/ui/.storybook/preview.ts
packages/ui/global.css
packages/ui/nativewind-env.d.ts
packages/ui/package.json
packages/ui/src/button/button.stories.tsx
packages/ui/src/button/button.tsx
packages/ui/src/index.ts
packages/ui/tailwind.config.ts
packages/ui/tsconfig.build.json
packages/ui/tsconfig.json
pnpm-lock.yaml

- 스토리북 연동했습니다.
- 빌드랑 가져와서 사용하는 부분은 한번 더 보긴 해야할 것 같아요.
- config-tailwind 빼서 공통으로 관리하는 것도 필요합니다.

feat: ✨ ui storybook

---

apps/dog-walk/app/(tabs)/index.tsx
apps/dog-walk/app/_layout.tsx
apps/dog-walk/components/CustomSafeAriaView.tsx
apps/dog-walk/components/card/CourseCard.tsx
apps/dog-walk/components/card/ReviewCard.tsx

- Home UI 구현
- 코드에서 변경된 부분을 자세히 설명해주세요.
- pnpm start

feat(dog-walk): Home UI 구현

---

.vscode/extensions.json

- yaml single quote, double quote 포맷 해결을 위해 패키지 추가합니다.
- #67 
- 설치하면 저장할 때 이상 없을 것 같습니다~

chore: 🔧 yaml 권장 패키지 추가

---

.github/workflows/reviewdog.yml
.vscode/cspell.json
.vscode/extensions.json

- ci에서 스펠체크 빼고, 에디터에서 확인하게 cspell 패키지 추가했습니다.
- https://github.com/infinite-loop-factory/app-factory/pull/64#discussion_r1903086642

ci: 👷 misspell 삭제

---

apps/delivery/app/(tabs)/index.tsx
apps/delivery/app/(tabs)/mypage.tsx
apps/delivery/components/shopping/shopping.article.tsx
apps/delivery/components/shopping/shopping.image.tsx

- mypage ui 구현
- https://github.com/infinite-loop-factory/app-factory/issues/24

feat: ✨ mypage implementation

---

apps/delivery/app/(tabs)/orderHistory.tsx
apps/delivery/components/order/OrderArticle.tsx

- 이 PR에서 변경된 내용에 대한 간단한 설명을 작성해주세요.
상세페이지 구현
- https://github.com/infinite-loop-factory/app-factory/issues/24

feat: ✨ detailed page implementation

---

apps/reaction-speed-test/app/(pages)/index.tsx
apps/reaction-speed-test/app/(pages)/measurement.tsx
apps/reaction-speed-test/app/(pages)/menu.tsx
apps/reaction-speed-test/app/(pages)/results.tsx
apps/reaction-speed-test/app/(pages)/settings.tsx
apps/reaction-speed-test/app/(pages)/signup.tsx
apps/reaction-speed-test/app/_layout.tsx
apps/reaction-speed-test/components/login/LoginForm.tsx
apps/reaction-speed-test/components/ui/form-control/index.tsx
apps/reaction-speed-test/components/ui/icon/index.tsx
apps/reaction-speed-test/components/ui/icon/index.web.tsx
apps/reaction-speed-test/components/ui/input/index.tsx
apps/reaction-speed-test/components/ui/vstack/index.tsx
apps/reaction-speed-test/components/ui/vstack/index.web.tsx
apps/reaction-speed-test/components/ui/vstack/styles.tsx
apps/reaction-speed-test/package.json
apps/reaction-speed-test/services/index.ts
apps/reaction-speed-test/services/user.ts
pnpm-lock.yaml

- `supabase Authentication` 활용해서 회원가입, 로그인 구현
- `/apps/reaction-speed-test/components/ui/*` 글루스택으로 추가된 파일은 확인 불필요
- #55 
- <img width="1166" alt="image" src="https://github.com/user-attachments/assets/b175e137-e0c2-4781-b6d6-6f7764f28de7" />
- `/apps/reaction-speed-test`에서 `pnpm run start`

reaction-speed-test 회원가입 | 로그인

---

apps/country-tracker/package.json
apps/country-tracker/src/app/(tabs)/_layout.tsx
apps/country-tracker/src/components/ParallaxScrollView.tsx
apps/country-tracker/src/components/ui/switch/index.tsx
apps/country-tracker/src/features/home/components/home-screen.tsx
apps/country-tracker/src/features/settings/components/settings-screen.tsx
apps/country-tracker/src/hooks/useThemeColor.ts
apps/country-tracker/tailwind.config.ts
pnpm-lock.yaml

- 홈이랑 설정 레이아웃 잡고 테마 적용했습니다.
- close #84 
| 홈 | 설정 |
| --- | --- |
| <img width="923" alt="Screenshot 2025-02-15 at 20 06 51" src="https://github.com/user-attachments/assets/3fd7deb0-8781-4147-89e2-ca15427e6154" /> | <img width="921" alt="Screenshot 2025-02-15 at 20 07 45" src="https://github.com/user-attachments/assets/56d4a33e-5ecd-47d5-9cdc-5fb9c0d6985c" /> |
- 테마 적용하게 Class로 바꿔주고, 토글할 때 바뀌게 해줬습니다.
- 코드 변경 사항을 테스트하는 방법을 적어주세요.
1. 테스트 시나리오 1
2. 테스트 시나리오 2
3. 테스트 시나리오 3
- 어떤거는 네이티브윈드가 먹고, 어떤거는 Style로만 먹고 다 달라서 그냥 네이티브윈드를 안 쓰는 게 낫나 싶기도하네요 :cry:
- ts-expect-error 는 gluestack Switch 안에 activeThumbColor 타입이 나오지는 않았는데, 문서에는 사용하라고 나와있고, 웹에서 스위치썸네일 색상 변경하는데 쓰입니다~ [참조](https://gluestack.io/ui/docs/components/switch)

feat(country-tracker): ✨ 테마 적용

---

apps/country-tracker/src/features/settings/components/settings-screen.tsx
packages/common/src/native/setting.ts
packages/common/src/native/setting.types.ts

- 스토어 앱으로 나가는 링크를 추가했습니다.
- #25 
| 웹 | 앱 |
| --- | --- |
| <img width="873" alt="Screenshot 2025-03-08 at 22 27 49" src="https://github.com/user-attachments/assets/23b92e49-6d92-4cfc-a882-30496b8cf27e" /> |  <img width="378" alt="Screenshot 2025-03-08 at 22 31 43" src="https://github.com/user-attachments/assets/532dd678-6375-4250-8eae-62c5cfcb77f0" /> |
- `openStorePage` 함수만 봐주시면 됩니다.
- pnpm start country-tracker -> settings -> rate the app

feat: ✨ 앱 링크 추가

---

apps/country-tracker/package.json
apps/country-tracker/src/features/map/components/map-globe.native.tsx
apps/country-tracker/src/features/map/components/map-globe.web.tsx
apps/country-tracker/src/features/map/components/map-screen.tsx
packages/common/package.json
pnpm-lock.yaml

- 지구본 추가했습니다.
- #23 
- react-native-map 추가하고, 웹에서는 오류떠서 web.tsx 파일로 분리했습니다.
- `pnpm start country-tracker`
- 코드 리뷰어가 알아야 할 추가 정보가 있으면 적어주세요.

feat: 지구본 추가

---

apps/dog-walk/app/(screens)/_layout.tsx
apps/dog-walk/app/(screens)/detail/[id].tsx
apps/dog-walk/app/(tabs)/search.tsx
apps/dog-walk/app/_layout.tsx
apps/dog-walk/components/KakaoMap.tsx
apps/dog-walk/components/atoms/IconText.tsx
apps/dog-walk/components/card/CourseDetailCard.tsx
apps/dog-walk/components/organisms/DetailDescription.tsx
apps/dog-walk/components/organisms/DetailHeaderBar.tsx
apps/dog-walk/components/organisms/DetailMap.tsx
apps/dog-walk/components/organisms/Reviews.tsx

- 산책 검색 화면에 위치 데이터 마커 표시 추가
- 산책 코스 상세화면 개발
<p>산책 코스 검색 화면</p>
<p>산책코스 상세 화면 - 정보 탭</p>
<p>산책코스 상세 화면 - 지도 탭</p>
<p>산책코스 상세 화면 - 리뷰 탭</p>
- 코드에서 변경된 부분을 자세히 설명해주세요.
- 코드 변경 사항을 테스트하는 방법을 적어주세요.
app-factory/apps/dog-walk 경로에서 npx expo run:android 실행하면 됩니다.
- 웹뷰 관련 리렌더링이나 ios는 확인 중입니다.
- 그리고 추가 코드는 이후 PR에 반영하겠습니다.

feat(dog-walk): 검색 화면 마커 표시 추가 및 코스 상세 화면 구현

---

apps/country-tracker/src/app/(tabs)/_layout.tsx
apps/country-tracker/src/features/map/components/map-globe.native.tsx
apps/country-tracker/src/features/map/components/map-screen.tsx
apps/country-tracker/src/i18n/locales/en.json

- 지구본에서 국가 이동시 애니메이션 추가
- #98 
https://github.com/user-attachments/assets/15960725-65f7-4c27-a4e4-93571d636634
- 해당 지역으로 이동시 애니메이션 추가
- 경도 계산
- pnpm start country-tracker

feat(country-tracker): ✨ 지구본 이동 애니메이션

---

.github/copilot-instructions.md
apps/country-tracker/src/app/settings/license.tsx
apps/country-tracker/src/components/ParallaxScrollView.tsx
apps/country-tracker/src/features/settings/components/license-screen.tsx
apps/country-tracker/src/features/settings/components/settings-screen.tsx
apps/country-tracker/src/i18n/locales/en.json
apps/country-tracker/src/i18n/locales/ko.json

- 라이센스 페이지 추가
- 라이센스 스크린이랑 컴포넌트 추가했습니다.
- copilot-instructions.md 추가했습니다. 만들어달라고 했는데, chat 사용하면서 더 보강해볼게요 (해주셔도 됩니다)
- pnpm start country-trakcer
- 이어서 https://www.npmjs.com/package/license-checker-rseidelsohn 활용해서 라이센스 정보 가져와보려고 합니다.

feat(country-tracker): ✨ 라이센스 페이지

---

apps/cafe/src/app/(tabs)/category.tsx
apps/cafe/src/app/category/[id].tsx

- 카테고리 상세 페이지 구현
- https://github.com/infinite-loop-factory/app-factory/issues/101
- 코드 리뷰어가 알아야 할 추가 정보가 있으면 적어주세요.

feat: ✨ implement category detail page

---

apps/cafe/src/features/shared/hooks/useThemeColor.ts
apps/country-tracker/src/app/_layout.tsx
apps/delivery/app/_layout.tsx
apps/delivery/components/web-layout/WebviewLayout.tsx
apps/delivery/features/order/api/index.ts
apps/delivery/features/shared/hooks/useThemeColor.ts
apps/dog-walk/app/_layout.tsx
apps/dog-walk/components/ui/icon/index.web.tsx
biome.json
pnpm-lock.yaml
pnpm-workspace.yaml

- 바이옴2 적용했습니다.
- import 정렬을 추가해두었습니다.
- `**/components/ui/**/*.ts*`는 글루스택에서 생성되는 파일이라 예외처리 했습니다.
- 기존과 동일

feat: ✨ biome 2

---

apps/country-tracker/app.config.ts
apps/country-tracker/eas.json
apps/country-tracker/package.json
apps/country-tracker/src/app/_layout.tsx
apps/country-tracker/src/app/login.tsx
apps/country-tracker/src/libs/jotai.ts
pnpm-lock.yaml
scripts/start.ts

- eas ios build 추가했습니다.
- eas.json 추가
- eas-dev-client 및 --dev 실행 추가
- jotai 스토어 하나로 변경
- pnpm start country-tracker --dev

feat(country-tracker): ✨ local build

---

apps/country-tracker/src/features/map/components/map-screen.tsx

- 간단하게 양쪽 패딩 수정했습니다.
- class가 안 먹어서 컴포넌트에 직접 패딩 추가
- pnpm start country-tracker

fix(country-tracker): 🐛 bottom sheet padding

---

apps/playlist/app/(tabs)/index.tsx

- implement artist-specific song list modal

feat: ✨ implement artist-specific song list modal

---

apps/cafe/src/app/(tabs)/category.tsx

- 리뷰 작성 폼 구현
- 
- https://github.com/infinite-loop-factory/app-factory/issues/101
- 코드 리뷰어가 알아야 할 추가 정보가 있으면 적어주세요.

feat: ✨ implement category search
